### ISSUE TITLE
Write Shownotes

### ISSUE THREAD

**Issue by hoodie** [naming-things/internal#2]

**Comment by kiliankoe** [comment]
Just dumping here:

- Bullet Journal http://bulletjournal.com
  - Leicht angepasste Variante einer YouTuberin https://www.youtube.com/watch?v=vtjWgiecORI
- Unsere Podcastclients
  - BeyondPod http://beyondpod.mobi/android/index.htm
  - Overcast https://overcast.fm
- Podcast Empfehlungen
  - DRadio Hörsaal
  - DRadio Wissen
  - DRadio Update
  - DRadio Einhundert
  - 99% Invisible
  - Radiolab
  - Startup von Gimlet
  - Reply All
  - Dan Carlin's Harcore History
  - Hoaxilla
  - No Such Things as a Fish
  - ATP (Accidental Tech Podcast)
  - Surprisingly Awesome
- Bitlove https://bitlove.org
- IPFS https://ipfs.io
- Maidsafe https://maidsafe.net
- Unser "Sponsor" Kolle-Mate http://kolle-mate.de
- Das ascii https://ascii-dresden.de
- Emojicode http://www.emojicode.org

**Comment by kiliankoe** [comment]
Still missing a few shownotes for episode 0.
