### ISSUE TITLE
Solve Hosting Issue

### ISSUE THREAD

**Issue by hoodie** [naming-things/internal#3]
## Options:

* [ ] IPFS
* [ ] Github
* [ ] archive.org
* [ ] vhost
* [ ] ???

**Comment by kiliankoe** [comment]
Just to list additional options to the ones you already listed:

- AWS
- Uberspace
- Git LFS (only if GitHub publishes HTTP URLs to these files as well)
- University servers (probably not a good idea 😄)
- Soundcloud
- ...?

**Comment by kiliankoe** [comment]
These are the external services directly supported by Auphonic by the way:

<img width="559" alt="screen shot 2017-01-16 at 00 08 07" src="https://cloud.githubusercontent.com/assets/2625584/21967044/ef987262-db7f-11e6-80d7-70f0dec3081a.png">

**Comment by kiliankoe** [comment]
Using SoundCloud (at least for now). Haven't configured Auphonic for auto-publishing yet.
