### ISSUE TITLE
Understand Auphonic

### ISSUE THREAD

**Issue by hoodie** [naming-things/internal#4]
Please document process here

**Comment by kiliankoe** [comment]
Tried out the desktop client, didn't see a few options of the *AAS version though, which might be easier to work with. Desktop client is a 7-day trial and then fixed price. Hosted might cost a bit more in the long run obviously, but might be worth it.

**Comment by kiliankoe** [comment]
Webclient looks really nice actually, having a lot of fun playing around with that. And I kinda like that re-encoding an already uploaded file is not counted against your quota (unless it's been deleted after 21 days I believe).
